### PR TITLE
mediatek: add support for Routerich AX3000

### PR DESCRIPTION
**Pull request by csharper2005**
Routerich AX3000 is a wireless WiFi 6 router.

Specification
-------------
- SoC       : MediaTek MT7981BA dual-core ARM Cortex-A53 1.3 GHz
- RAM       : DDR3 256 MiB (ESMT M15T2G16128A)
- Flash     : SPI-NAND 128 MiB (ESMT F50L1G41LB)
- WLAN      : MediaTek MT7976CN dual-band WiFi 6
  - 2.4 GHz : b/g/n/ax, MIMO 2x2
  - 5 GHz   : a/n/ac/ax, MIMO 2x2
- Ethernet  : 10/100/1000 Mbps x4 (MediaTek MT7531AE)
- USB       : 1x 2.0
- UART      : through-hole on PCB
  - [J500] GND, TX, RX, 3.3V (115200n8)
- Buttons   : Mesh, Reset
- LEDs      : 1x Power (Blue)
              1x WiFi 2.4 GHz (Blue)
              1x WiFi 5 GHz (Red)
              1x Mesh (Blue)
              3x LAN activity (Blue)
              1x WAN activity (Blue)
              2x WAN no-internet (Red)
- Power     : 12 VDC, 1.5 A

Installation
------------
Flash OpenWrt 'sysupgrade.bin' image using stock firmware web-interface (without keeping settings).

Return to stock
---------------
Install stock firmware image (without keeping settings) using OpenWrt sysupgrade method.

Recovery
--------
Connect uart, use u-boot menu to flash stock firmware image or boot OpenWrt initramfs image.

MAC addresses
-------------
```
+---------+-------------------+-----------+
|         | MAC               | Algorithm |
+---------+-------------------+-----------+
| WAN     | 24:0f:5e:xx:xx:b4 | label     |
| LAN     | 24:0f:5e:xx:xx:b5 | label+1   |
| WLAN 2g | 24:0f:5e:xx:xx:b6 | label+2   |
| WLAN 5g | 24:0f:5e:xx:xx:b7 | label+3   |
+---------+-------------------+-----------+
```
The WLAN 2g MAC was found in 'Factory', 0x4

### CODE REVIEW

**Comment by zjuahhy** [comment]
this device is same as zr-3020 produced by Shenzhen Z-Router

**Comment by csharper2005** [comment]
> this device is same as zr-3020 produced by Shenzhen Z-Router

Where did you get this information from?

The devices have different spi-nand chips, different LEDs (colours, functions and gpio matchings). Additionally, ax3000 has a USB. So, they can't be the same.

**Comment by csharper2005** [comment]
> this device is same as zr-3020 produced by Shenzhen Z-Router

Do you mean this device? https://github.com/hanwckf/immortalwrt-mt798x/blob/openwrt-21.02/target/linux/mediatek/files-5.4/arch/arm64/boot/dts/mediatek/mt7981-zr-3020.dts

1. The LEDs colours and gpios are slightly different;
2. That Zr-3020 has different spi-nand chip (silabs);
3. As far I understand Zr-3020 has no usb.

**Comment by romanovj** [comment]
`mediatek,u3p-dis-msk = <0x0>;`
maybe 0x1?

**Pull request merged**
